### ISSUE TITLE
FCNN visualization does not respect the "show input-layer" option

### ISSUE THREAD

**Issue by logalyst** [NormanTUD/asanAI#5]
![image](https://github.com/NormanTUD/asanAI/assets/48360062/0f222e06-25be-442d-9bb8-a29576836371)

![image](https://github.com/NormanTUD/asanAI/assets/48360062/6b91b9b2-aa61-4e12-b7d8-f9a13f863eea)

**Comment by NormanTUD** [comment]
Partially fixed in e27bdf1e328d2128f61c210a45b37e0bc50e5a36. It's now respected, but I need to render it as Conv Layer because I am not sure how to render it exactly. It now has the nr. of channels (last element of input shape) as number of elements.
